spring:
  datasource:  # 配置mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.180.45:3306/user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1234567890

  jpa:
    #hibernate:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true
  mvc:
    static-path-pattern: /**    # 允许所有静态资源路径
  web:
    resources:
      static-locations: classpath:/static/  # 静态资源目录

jwt:
  secret: "123"
    
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    dentist.dentist.UserService: DEBUG # 按需调整日志级别
  file:
    name: logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
server:
  address: 0.0.0.0
  port: 8080  # 默认端口
  

